bg_tit: &bg_tit {stack: [{background: {color: 5faf5fff}}, {underline: {size: 3, color: ea6962ff}}]}
bg_tot: &bg_tot {underline: {size: 3, color: ea6962ff}}
bg_bat: &bg_bat {stack: [{background: {color: 28282800}}, {underline: {size: 3, color: 5f8700ff}}]}
hack: &hack mononoki Nerd Font:pixelsize=15
bar:
  height: 40
  location: top
  font: mononoki Nerd Font:pixelsize=11
  spacing: 2
  margin: 0
  layer: bottom
  foreground: eeeeeeff
  background: 1c1c1c00

  left:
    - river:
        font: mononoki Nerd Font:pixelsize=14:style:Bold
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13 
              tag: id 
              default: {empty: {}}
              values:
                1: {string: {text: ﳐ, font: *hack}}  
                2: {string: {text: , font: *hack}}  
                3: {string: {text: , font: *hack}}  
                4: {string: {text: , font: *hack}}  
                5: {string: {text: , font: *hack}}  
                6: {string: {text: , font: *hack}}  
                7: {string: {text: , font: *hack}}  
                8: {string: {text: , font: *hack}}  
                9: {string: {text: , font: *hack}}  
                10: {string: {text: "scratchpad", font: *hack}}  
                11: {string: {text: "work", font: *hack}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
            tag: state
            values:
              urgent:
                map:
                  <<: *river_base
                  deco: *bg_tit
              focused:
                map:
                  <<: *river_base
                  deco: *bg_tit
              unfocused:
                map:
                  <<: *river_base
              invisible:
                map:
                  tag: occupied
                  values:
                    false: {map: {<<: *river_base}}
                    true: {map: {<<: *river_base, deco: *bg_tot}}
  
  center:
    - river:
        title:
          map:
            tag: title
            default:
              string:
                text: "{title}"
                left-margin: 5
                right-margin: 5
                max: 50
                deco:
                  stack:
                    - underline:
                        size: 3
                        color: 14b2fcff
            values:
              "":
                empty: {}
        content:
          empty: {}

    - script:
        path: /home/uncomfy/.config/yambar/get_media.sh
        content:
          map:
            tag: status
            default:
               list:
                 spacing: 0
                 items:
                   - string:
                      font: mononoki Nerd Font:pixelsize=20
                      text: "" 
                      left-margin: 5
                      right-margin: 5
                      deco:
                        underline:
                          size: 3
                          color: 1DB954ff
                      foreground: 1DB954ff
                   - string:
                      text: "{status}"
                      left-margin: 5
                      right-margin: 5
                      foreground: 1DB954ff
                      deco:
                        underline:
                          size: 3
                          color: 1DB954ff
                      max: 50
                      on-click: 
                        right: flatpak run com.spotify.Client
                        left: /home/uncomfy/.config/yambar/play_pause_media.sh
                        wheel-up: playerctl -p spotify previous
                        wheel-down: playerctl -p spotify next
            values:
              "":
                empty: {}


  right:
    - backlight:
        name: intel_backlight
        content:
          string:
            left-margin: 5
            right-margin: 5
            text: " {percent}%"
            foreground: eeeeeeff
            deco:
              underline:
                size: 3
                color: f7e202ff
            on-click:
              wheel-up: /home/uncomfy/.config/yambar/brightnessup.sh 
              wheel-down: /home/uncomfy/.config/yambar/brightnessdown.sh
    - network:
        name: enp7s0
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: " {name}", foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: 
                          string:
                            foreground: eeeeeeff
                            right-margin: 5
                            left-margin: 5
                            text: " {name}"
                            deco:
                              underline:
                                size: 3
                                color: f702beff
                        values:
                          "":
                            string: 
                              right-margin: 5
                              left-margin: 5
                              text: " {name}" 
                              foreground: eeeeeeff
                              deco:
                                underline:
                                  size: 3
                                  color: f702beff
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            tag: online
            values:
              false: {string: {text: , foreground: 444444ff}}
              true:
                map:
                  on-click:
                    left: pamixer -t
                    wheel-down: /home/uncomfy/.config/yambar/volumeup.sh 
                    wheel-up: /home/uncomfy/.config/yambar/volumedown.sh
                  tag: muted
                  values:
                    true:
                      string:
                        text: " Muted"
                        foreground: ea6962ff
                        right-margin: 5
                        left-margin: 5
                        deco:
                          underline:
                            size: 3
                            color: ddddddff
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string:
                              text: " {percent}"
                              foreground: eeeeeeff
                              right-margin: 5
                              left-margin: 5
                              deco:
                                underline:
                                  size: 3
                                  color: 020202ff
                          - string:
                              text: " {percent}"
                              foreground: eeeeeeff
                              right-margin: 5
                              left-margin: 5
                              deco:
                                underline:
                                  size: 3
                                  color: 95E7EAff
                          - string: 
                              text: " {percent}"
                              foreground: eeeeeeff
                              right-margin: 5
                              left-margin: 5
                              deco:
                                underline:
                                  size: 3
                                  color: 95E7EAff
                          - string:
                              text: " {percent}"
                              foreground: eeeeeeff
                              right-margin: 5
                              left-margin: 5
                              deco:
                                underline:
                                  size: 3
                                  color: 95E7EAff
                          - string:
                              text: " {percent}"
                              foreground: eeeeeeff
                              right-margin: 5
                              left-margin: 5
                              deco:
                                underline:
                                  size: 3
                                  color: 95E7EAff
    - network:
        name: wlp0s20f3
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: " {name}", foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: 
                          string:
                            foreground: eeeeeeff
                            right-margin: 5
                            left-margin: 5
                            text: " {name}"
                            deco:
                              underline:
                                size: 3
                                color: f702beff
                        values:
                          "":
                            string: 
                              right-margin: 5
                              left-margin: 5
                              text: " {name}" 
                              foreground: eeeeeeff
                              deco:
                                underline:
                                  size: 3
                                  color: f702beff
    - battery:
        name: BAT1
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                      - string: {text: " ", foreground: eeeeeeff, left-margin: 2, right-margin: 5, deco: *bg_bat}
                - string: {text: "{capacity}% {estimate}", deco: *bg_bat, foreground: eeeeeeff, right-margin: 5, left-margin: 5}
              charging:
                - string: {text: " ", foreground: eeeeeeff, left-margin: 5, right-margin: 5, deco: *bg_bat}
                - string: {text: "{capacity}% {estimate}", left-margin: 2, right-margin: 5, deco: *bg_bat}
              full:
                - string: {text: " ", foreground: eeeeeeff, left-margin: 5, right-margin: 5, deco: *bg_bat}
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                      - string: {text:  , foreground: eeeeeeff, left-margin: 2, right-margin: 5}
                - string: {text: "{capacity}%", foreground: ffffffff, deco: *bg_bat}
    - clock:
        time-format: "%H:%M:%S %Z"
        content:
          list:
            spacing: 0
            items:
            - string:
                text: " {date}"
                right-margin: 5
                left-margin: 5
                foreground: eeeeeeff
                deco:
                  underline:
                    size: 3
                    color: 35b9abff
            - string:
                right-margin: 0
                left-margin: 5
                foreground: eeeeeeff
                text: " {time}"
                deco:
                  underline:
                    size: 3
                    color: 35b9abff
    - script:
        path: /home/uncomfy/.config/yambar/get_cpu.sh
        args: [1]
        content:
          - string:
              text: " {cpu}%"
              left-margin: 4
              deco:
                underline:
                  size: 3
                  color: f76802ff
    - script:
        path: /home/uncomfy/.config/yambar/pacman.sh
        args: []
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: " "
                  left-margin: 1
                  font: mononoki Nerd Font:pixelsize=16:style:Bold
                  deco:
                    underline:
                      size: 3
                      color: 73ba25ff
              - string:
                  text: "{pacman} + {aur} = {pkg}"
                  right-margin: 5
                  deco:
                    underline:
                      size: 3
                      color: 73ba25ff
