#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
# Setting some startup stuff



# Binding to reload the configuration (good for edits on bindings or adding new stuff
riverctl map normal "Mod4" R spawn $HOME/.config/river/init

# Setting some startup stuff
riverctl spawn "river-tag-overlay --background-colour 0x2e3440 --border-colour 0x000000 --square-active-occupied-colour 0x84bcbb --square-active-background-colour 0x000000 --square-active-border-colour 0x81a1c1 --tag-amount 11 --anchors 1:0:0:0"
riverctl spawn "wlsunset -l 8.17 -L 123.80"
riverctl spawn $HOME/.config/river/wlsunset.sh
riverctl spawn $HOME/.config/mako/mako.sh
riverctl spawn $HOME/.config/river/swaybg.sh
riverctl spawn $HOME/.config/river/bindings.sh
riverctl spawn $HOME/.config/waybar/waybar.sh
riverctl spawn $HOME/.config/pipewire.sh

# Borders
riverctl border-color-focused 0x81a1c1ff
riverctl border-color-unfocused 0xe5e9f0dd
riverctl border-width 2
riverctl background-color 0x282828

# DBUS
exec "dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
